// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var veri = artifacts.require('Verifier');
var proofs = require('../proofs.js');
// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps
let proof = proofs[0];
it('Test verification with correct proof', async function () { 
try{
    this.contract = await veri.new();
    // TODO: mint multiple tokens
    // console.log("proof! ", proof.proof.a, proof.proof.b, proof.proof.c, proof.proof.inputs);
    let result = await this.contract.verifyTx(proof.proof.a, proof.proof.b, proof.proof.c, proof.inputs);
    console.log(result.receipt.status);
    assert.equal(result.receipt.status, true, "Test verification with correct proof");
}
catch(e){
    console.log(e," : ", e.message);
}
})
    
// Test verification with incorrect proof
let unvalid = proofs[10];
it('Test verification with incorrect proof', async function () { 
    try{
        this.contract = await veri.new();
        // TODO: mint multiple tokens
        // console.log("proof! ", proof.proof.a, proof.proof.b, proof.proof.c, proof.proof.inputs);
        let result = await this.contract.verifyTx(unvalid.proof.a, unvalid.proof.b, unvalid.proof.c, unvalid.inputs);
        console.log(result.receipt.status);
        
    }
    catch(e){
        assert.equal(e, e, "Test verification with incorrect proof");
    }
    })